name: Build and Release

on:
  push:
    branches:
      - master
    tags:
      - "v*"
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: gradle
      - name: Set execution flag for gradlew
        run: chmod +x gradlew
      - name: Build library AAR and sample APK
        run: ./gradlew :dsmpokedex:assembleRelease :app:assembleDebug --stacktrace
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: |
            dsmpokedex/build/outputs/aar/dsmpokedex-release.aar
            app/build/outputs/apk/debug/app-debug.apk

  release:
    name: Release
    needs: build
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: artifacts
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.run_number }}
          name: ${{ github.event.repository.name }} v${{ github.run_number }}
          files: |
            dsmpokedex-release.aar
            app-debug.apk
